### ISSUE TITLE
EventSimulator simulate key does not use modifiers

### ISSUE THREAD

**Issue by lerrific** [TolikPylypchuk/SharpHook#1]
I created a new .net 5 console application, installed SharpHook via nuget and used only this code from the documentation, it does not seem to press the ctrl key, or any other modifier key for that matter. tried it in Notepad, Visual Studio etc.
```
var simulator = new EventSimulator();

simulator.SimulateKeyPress(KeyCode.VcC, ModifierMask.LeftCtrl);   // Press Ctrl+C
simulator.SimulateKeyRelease(KeyCode.VcC, ModifierMask.LeftCtrl); // Release Ctrl+C
```
on windows 10

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for posting this issue. I'll investigate it over the weekend. In the meantime, you use this workaround:

```C#
simulator.SimulateKeyPress(KeyCode.VcLeftControl);   // Press Ctrl
simulator.SimulateKeyPress(KeyCode.VcC);   // Press C
simulator.SimulateKeyRelease(KeyCode.VcC); // Release C
simulator.SimulateKeyRelease(KeyCode.VcLeftControl); // Release Ctrl
```

**Comment by TolikPylypchuk** [comment]
I've looked into this issue, and unfortunately, I can't fix it as this is an issue of libuiohook itself. It doesn't seem to take the modifier masks into account on Windows (on macOS and Linux it does though). I've created [an issue](https://github.com/kwhat/libuiohook/issues/111) in libuiohook's repo.

I don't want to fix it here, because I want SharpHook to be a thin wrapper of libuiohook, without too many assumptions about its behavior. I will document this bug though so that users are aware of it.

I'll keep this issue open until it's fixed in libuiohook. In the meantime, you can always work around it using the method I've described in the previous comment - you don't strictly _need_ the modifier mask on the event.

**Comment by TolikPylypchuk** [comment]
Turns out that on Windows it's not possible to simulate events with modifiers the same way as it is on macOS and Linux. The author of libuiohook has decided to remove support for simulating events with modifiers on macOS and Linux for a uniform experience across different platforms. So starting with version 3.0.0 (which I've just released) the methods in `IEventSimulator` don't accept the event mask at all.

The workaround I have wrote about previously is now the official way to simulate an key press with a modifier. This means that this issue is resolved even though it's not exactly fixed.
