### ISSUE TITLE
Mouse movement event doesn't trigger while mouse button held down

### ISSUE THREAD

**Issue by elmuffo** [TolikPylypchuk/SharpHook#103]
Using the below code on Debian 12 XFCE Xorg (or Fedora 39 KDE Wayland), the program only outputs while no mouse buttons are held down - if I hold down Button1 then no output is received until the mouse is moved _after_ Button1 has been released.

I tried testing it with sudo but that didn't change anything

```
var hook = new SimpleGlobalHook();
hook.MouseMoved += (object? sender, e as MouseHookEventArgs e) =>
{
    Console.WriteLine("movement");
};
await hook.RunAsync();

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for posting this issue!

This is actually expected behavior since global hooks have another event - `MouseDragged` - just for this case when a mouse is moved with a button down.

Could you please try subscribing to the `MouseDragged` event and test it out? If it works then the issue can be closed.

As for why this is a separate event - I don't know, this is how it works in libuiohook.

**Comment by TolikPylypchuk** [comment]
Also, SharpHook doesn't support Wayland at all at the moment. Only X11 is supported. Wayland support is [in progress in libuiohook](https://github.com/kwhat/libuiohook/pull/180) - the library SharpHook wraps - but not yet here.

**Comment by elmuffo** [comment]
Hi, thanks - the MouseDragged event works for my case
