### ISSUE TITLE
Simulation of keys while NumLock is on

### ISSUE THREAD

**Issue by Butcher-vj** [TolikPylypchuk/SharpHook#105]
sharpHook.Native Event simulator :
In windows, while trying to simulate a ArrowUp, ArrowLeft, ArrowRight and ArrowDown keys with numlock being on in the remote machine, results in simulating like 8 for ArrowUp and 6 for ArrowRight and 4 for ArrowLeft and 2 for ArrowDown.

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for posting this issue! I've fixed a [similar problem](https://github.com/TolikPylypchuk/SharpHook/issues/102) in the latest version - 5.3.4. Could you please make sure that you're using the latest version? I've just tried to reproduce it, and everything works fine for me. If you are using the latest version, and the problem is present, then I will think about the cause and how to fix it.

**Comment by Butcher-vj** [comment]
> Hi! Thanks for posting this issue! I've fixed a [similar problem](https://github.com/TolikPylypchuk/SharpHook/issues/102) in the latest version - 5.3.4. Could you please make sure that you're using the latest version? I've just tried to reproduce it, and everything works fine for me. If you are using the latest version, and the problem is present, then I will think about the cause and how to fix it.

Thanks for letting me know.
I have been using 5.3.1 version, now after updated to 5.3.4 its working fine.
