### ISSUE TITLE
error running example project: Unable to load DLL 'uiohook' or one of its dependencies: The specified module could not be found. (0x8007007E)

### ISSUE THREAD

**Issue by LiorBanai** [TolikPylypchuk/SharpHook#32]
When I try to run the example I'm getting the following error: Unable to load DLL 'uiohook' or one of its dependencies: The specified module could not be found. (0x8007007E)

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for posting this issue! In order to run the sample project, make sure you do everything that's specified in the readme about [building from source](https://github.com/TolikPylypchuk/SharpHook#building-from-source).

If you did copy the libuiohook binaries into the correct folder and the project doesn't work, then make sure you select a platform explicitly; don't use `AnyCPU`. If you did specify the platform and the sample project still doesn't work, then we have a problem that I'll need to investigate further.

**Comment by LiorBanai** [comment]
Yeah it was AnyCPU . Thanks
