### ISSUE TITLE
The method CreateScreenInfo is causing app crash

### ISSUE THREAD

**Issue by Chris3773** [TolikPylypchuk/SharpHook#40]
When trying to get the screen info using the managed version of `UioHook.CreateScreenInfo()` the app will randomly crash with a 3221226356 return code. That return code is usually for an access violation, buffer overflow, stack overflow, invalid pointer or interop issues.

It looks like it may be a problem with the native `libuiohook` lib as just calling `UioHook.CreateScreenInfo(out byte count)` will produce the same error.

Here is an example code that I was able to reproduce, keep in mind it's random, and may need to be restarted a few times.

```
using SharpHook.Native;

Task.Run(async () =>
{
    while (true)
    {
        var screenInfo = UioHook.CreateScreenInfo()
            .OrderBy(x => x.Number)
            .FirstOrDefault();

        Console.WriteLine($"Screen: [Width: {screenInfo.Width}, Height: {screenInfo.Height}]");

        await Task.Delay(50);
    }
});

Console.ReadLine();
```

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for using SharpHook! I will look into this issue and try to reproduce it over the weekend. In the meantime, could you please tell me which OS you're using?

**Comment by Chris3773** [comment]
Windows 10 with 3 displays at 4k and 200% scale.

**Comment by TolikPylypchuk** [comment]
I've tried to reproduce the issue (using just my laptop's screen and connecting my 4K TV as a second screen) and couldn't reproduce it - ran your code multiple times, but it didn't crash.

I'm going to keep this issue open, but I don't know what can be done about it.

**Comment by Chris3773** [comment]
I ran the test on a few different setups and the only setup I was able to reproduce it is the 3 displays at 4k. I was able to reproduce it on the 3 displays at 4k with two different computers.

**Comment by TolikPylypchuk** [comment]
OK, I'll try to reproduce this issue with 3 screens in the coming days then.

**Comment by GuruGurra** [comment]
Any news on this problem?

I have a couple of users getting problems, and they all have three screens. 
The response they get seems to be random and totally wrong; one example:

Screen number=0, X=1536, Y=0, Width=1536, Height=960
Screen number=108, X=388, Y=0, Width=37904, Height=53100
Screen number=2, X=0, Y=0, Width=1536, Height=960

**Comment by TolikPylypchuk** [comment]
No news, sorry :(

I didn't have a chance to get a three-screen setup to reproduce this issue.

Could you please enable [libuiohook logs on the DEBUG level](https://sharphook.tolik.io/v4.2.0/articles/logging.html) and see whether the screen info it logs is also wrong? If it's also wrong then the issue is with libuiohook itself, and you should probably create an issue in [the original libuiohook repository](https://github.com/kwhat/libuiohook). If it's correct there and wrong in SharpHook, well, that would be really interesting.

**Comment by GuruGurra** [comment]
All I say in this post is about Windows. I feel the same problem exists on Mac, but I haven't confirmed this.

This is logged:

MessageLogged           [monitor_enum_proc [72]: Monitor 1: 3840x2160 (0, 0)]
MessageLogged           [monitor_enum_proc [72]: Monitor 2: 3840x2160 (5760, 0)]
MessageLogged           [monitor_enum_proc [72]: Monitor 3: 1536x1152 (11520, 0)]
GetDisplays                   [Display Number=(0), X=(0), Y=(0), Width=(3840), Height=(2160)]
GetDisplays                   [Display Number=(234), X=(32765), Y=(0), Width=(63824), Height=(33260)]
GetDisplays                   [Display Number=(2), X=(11520), Y=(0), Width=(1536), Height=(1152)]

The "MessageLogged" entries are from libuiohook log; the "GetDisplays" entries are what I get back from the CreateScreenInfo() call. As can be seen, libuiohook has the correct information, but this is not returned by SharpHook.

What is worse is that a call to CreateScreenInfo() will cause the app to crash in an "Exception code: 0xc0000374" (heap corruption) error at random places in the code. The heap corruption exception is not thrown at the CreateScreenInfo() call but can come anywhere and is very random. Sometimes the app survives a call to CreateScreenInfo(), but it will eventually fail with a heap corruption exception. 

- A call to CreateScreenInfo() with 2 monitors never fails. The monitor info is correct, and no heap corruption exceptions.
- A call to CreateScreenInfo() with 3 monitors fails most of the time. The monitor info is incorrect every time, and heap corruption exceptions are thrown most of the time.

A "manual" P/Invoke call to EnumDisplayMonitors to get the monitor information always gives the correct information and is not causing the app to crash.

**Comment by TolikPylypchuk** [comment]
Huh, that's really interesting. I guess then that either the ScreenData struct is incorrectly defined in SharpHook, and there's something wrong with the P/Invoked method. I'll look into it shortly - hopefully I can spot the problem without needing 3 screens.

**Comment by GuruGurra** [comment]
If you have 2 screens, you can add a mobile or tablet as a 3rd screen using the SpaceDesk app; that's what I did.

https://www.spacedesk.net/

**Comment by TolikPylypchuk** [comment]
OK, so I've managed to create a setup with 3 screens and reproduce the issue thanks to your advice. After a couple hours of debugging the issue, I've discovered that the issue was in libuiohook after all.

Long story short, the function for getting screen info in libuiohook allocated memory and dynamically expanded it using `realloc`. It passed a wrong size to it which meant that it was in the realm of undefined behavior - I'm actually surprised that the function worked consistently for 2 screens.

I've submitted [an issue](https://github.com/kwhat/libuiohook/issues/163) and [a pull request with a fix](https://github.com/kwhat/libuiohook/pull/164) to the original libuiohook repo, but since SharpHook uses [a fork](https://github.com/TolikPylypchuk/libuiohook), I don't need to wait for it to get merged - in fact, I've already released version 4.2.1 which contains the fix for this issue.

If you encounter other issues with getting screen info, then let me know - I'm sure they will be easier to fix since now I know how to set up multiple screens :)

**Comment by TolikPylypchuk** [comment]
Before realizing that the issue was in libuiohook, I thought that it was an issue with marshalling the data into C# and went as far as analyzing actual bytes that were returned from the function - a fun way to spend a Sunday evening :)

![image](https://github.com/TolikPylypchuk/SharpHook/assets/11243860/943920fe-4dea-4f07-becc-cdc64d1a5206)

**Comment by GuruGurra** [comment]
Great, thanks. 

Can you say if this problem also affected macOS?

**Comment by TolikPylypchuk** [comment]
No, the problem was in Windows-specific code. If there's a problem with macOS then it's a different one - and one that I won't be able to fix at the moment since I don't have a Mac.
