### ISSUE TITLE
Pressing backspace destroys console output

### ISSUE THREAD

**Issue by ScottKane** [TolikPylypchuk/SharpHook#43]
```cs
_hook.KeyTyped.Subscribe(e =>
{
    if (e.Data.KeyCode is KeyCode.VcBackspace && _input != string.Empty)
        _input = _input[..^1];
    else if (e.Data.KeyCode is not KeyCode.VcEnter && e.Data.KeyCode is not KeyCode.VcBackspace)
        _input += (char)e.Data.KeyChar;
    
    _layout = CreateLayout(string.Join(string.Empty, _input.Reverse().Take(AnsiConsole.Profile.Width - 4).Reverse()));
});
_hook.KeyPressed.Subscribe(e =>
{
    if (e.RawEvent.Mask.HasFlag(ModifierMask.LeftCtrl))
    {
        if (e.Data.KeyCode == KeyCode.VcC)
            Cancel();
        if (e.Data.KeyCode == KeyCode.VcBackspace)
            _input = string.Empty;
    }
});
```

The only backspace events I let through are to empty out a string, when the string is empty, none get through. However, when using these hooks, the user is just freely able to type into the console and destroy the output. Is this supposed to be happening, I just want to hook into input events, it shouldn't be changing the behavior as I shouldn't be writing into the input stream.

**Comment by ScottKane** [comment]
I just found `e.SuppressEvent` but it's either no input or write what you want to the console, I tried only suppressing the event when backspace is pressed and the input string is empty, that just ignores the suppression and lets you write and when I set it straight away it the subscription, it stops the console crap but then somehow the code in the subscription updating the input string isn't working

**Comment by ScottKane** [comment]
I also can't debug to see what's going on in VS or Rider so not sure what's going on there. Never had this from any package before. I'm assuming the debugger is locking something up in the native bindings causing the actual OS to chug along trying to process input but I can't be sure

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for opening this issue! Could you please provide a full reproducible example (a project would be ideal) so that I can test this behavior? I'm not really sure what exactly is going on based on your description, sorry.

I've just looked through the code of libuiohook and it looks like you can't suppress `KeyTyped` events. If you need to suppress keyboard input, you should suppress `KeyPressed` and `KeyReleased`. I'll mention this in the docs.

Regarding the debugging experience, there's issue #37, although I don't really know if anything can be done about this.

**Comment by TolikPylypchuk** [comment]
OK, I figured out why this problem occurs. It's because `KeyCode` is not available in `KeyTyped` events and is always equal to `VcUndefined`. So, inside the `KeyTyped` handler the `else if` branch will always be executed:

```c#
if (e.Data.KeyCode is KeyCode.VcBackspace && _input != string.Empty)
    _input = _input[..^1];
else if (e.Data.KeyCode is not KeyCode.VcEnter && e.Data.KeyCode is not KeyCode.VcBackspace)
    _input += (char)e.Data.KeyChar;
```

It's because `KeyCode` will never be equal to either `VcEnter` or `VcBackspace`, so when you press backspace, it actually appends the backspace character (`'\b'`) to the input string. I think that Spectre.Console simply can't handle the situation when there are too many backspace characters, and so the console output is broken.

To fix this you should instead exclusively check the `KeyChar` property:

```c#
char keyChar = (char)e.Data.KeyChar;
if (keyChar == '\b' && _input != string.Empty)
    _input = _input[..^1];
else if (keyChar != '\n' && keyChar != '\b')
    _input += keyChar;
```

Now it works as expected, and the output is not broken.

This behavior is not specified in the docs. In the next version I'll add a note that `KeyCode` and `RawCode` are not available in the `KeyTyped` event. Also, I'll add that `KeyTyped` and `MouseClicked` cannot be suppressed since they aren't OS events, but events created by libuiohook.

**Comment by ScottKane** [comment]
Thank you for your investigations, If I could have debugged the handlers I'm sure I would have noticed this.

Also, is there any way to determine if the current process is in focus or am I just hooked into all OS input events?

**Comment by TolikPylypchuk** [comment]
Well, I've found this out when debugging in VS. I don't know what problem you've been having, but in my case when a breakpoint was hit, the mouse cursor became slow for a couple seconds, then went back to normal.

As for determining whether the current process is in focus - the event handlers are global, so they are hooked into all OS input events, and if you want to know whether it was you process that would've gotten the input event, then you need some other way to do that.

**Comment by ScottKane** [comment]
Ok great, I had encountered the slow mouse issue described when debugging in either Rider or VS. After everything froze up for a good few seconds I just killed it. Maybe if I just give it a bit longer I will be able to debug properly. Thanks for the info regarding the hooks.
