### ISSUE TITLE
Unable to detect wither a cursor is visible or not on Linux

### ISSUE THREAD

**Issue by Sean-Zeo** [TolikPylypchuk/SharpHook#52]
Hi, would it be possible to add functionality to this to detect the visibility of a cursor across all platforms (working on linux specifically)?
This would be essential in order to switch between SimulateMouseMovement and SimulateMouseMovementRelative based on wither or not the cursor is visible (for fps games).

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for asking! I will look into it and let you know whether it can be added.

**Comment by TolikPylypchuk** [comment]
I've looked into this, and it looks like it's easy to achieve only on Windows (which has a `GetCursorInfo` function). On macOS there is the `CGCursorIsVisible` function which is deprecated and doesn't have a replacement. For X11 I wasn't able to find anything at all, unfortunately.

That said, I won't look into it further at this time since I have other stuff to implement first. I'll close this as a won't-fix, but we can continue this discussion. I'll also gladly accept a pull request.

**Comment by ZeoWorks** [comment]
Hi again friend, I haven't had any luck finding something for X11, perhaps xquerypointer?

**Comment by TolikPylypchuk** [comment]
Sorry @ZeoWorks, can't really help you with this as I don't know myself.
