### ISSUE TITLE
Events from the mouse or keyboard occur with a huge delay when debugging the breakpoint

### ISSUE THREAD

**Issue by magals** [TolikPylypchuk/SharpHook#68]
The library works well.
But if you debug (in VisualStudio 2022 Windows) the breakpoint in any part of the program, events from the mouse or keyboard occur with a huge delay (2-4 seconds). I tested this phenomenon on a computer and on a laptop, and the delay occurs in all variants. And the whole difficulty is that it is problematic to leave visual studio due to the delay

please tell me, have you observed such a phenomenon, if so, how do you maintain the convenience of debugging?

I got exactly the same phenomenon when using the LowLevelKeyboardListener object (I think you came across it, a well-known extension for capturing keys for Windows), when writing a Console / Asp net project

![image](https://github.com/TolikPylypchuk/SharpHook/assets/15940153/37bdeca4-0c08-44d4-a301-3e7db8d2ca06)

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for asking! Unfortunately, this is just the way global hooks work on Windows - it's not specific to SharpHook. There's nothing I can really do about it. Instead of putting breakpoints and freezing your system for a couple seconds, it's better to use `Debug.WriteLine` or [tracepoints](https://learn.microsoft.com/en-us/visualstudio/debugger/using-tracepoints?view=vs-2022) instead.

Issue #37 is the same issue, so I'm going to close this one as a duplicate.
