### ISSUE TITLE
Provide a way to simulate text entry also

### ISSUE THREAD

**Issue by akash07k** [TolikPylypchuk/SharpHook#7]
It's a very, very amazing library.
It has a lot of potential too.
I like the EventSimulator feature a lot.
However, I want to simulate the text entry also.
such as: "Akash".
Any way to accomplish that?
Or any plans to include this feature?

**Comment by TolikPylypchuk** [comment]
Hi! Thanks, I really appreciate the feedback!

Unfortunately, there is no way to simulate text entry as this feature is not present in libuiohook, and I imagine that it's non-trivial to implement since simulating text entry will require knowledge of the current keyboard layout and how the OS and the active window process key presses.

I'm going to close this issue as "won't fix" since I don't think it's going to be added to libuiohook, but feel free to discuss this further.

One thing you could do however is to use the clipboard. There's a library called [TextCopy](https://github.com/CopyText/TextCopy) which lets you work with the clipboard in a cross-platform way. Put the text you want to enter into the clipboard and then simulate pressing `Ctrl+V`. Obviously, this is a hack and not an ideal solution. Also, it will destroy anything that was in the clipboard previously, so use this with caution.

**Comment by akash07k** [comment]
Ok, I can understand,
But I think there's a native function called SendInput
[SendInput Function on MSDN](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendinput)
I think it can be implemented although it is not supported by libuiohook, but I think that it will provide more values to the users.

**Comment by TolikPylypchuk** [comment]
`SendInput` is precisely what libuiohook uses to simulate input events on Windows 🙂 

But, as I've said, simulating text entry is more difficult than simulating raw keystrokes. Also, I don't want to add anything to SharpHook which is not implemented in libuiohook because I'm absolutely not an expert in low-level input event manipulation and I can't guarantee that the added features will be any good.

**Comment by akash07k** [comment]
Ah, I understood.
No problem bro :-)

**Comment by TolikPylypchuk** [comment]
Hi @akash07k! FYI, I've implemented simulating text entry in libuiohook myself, and it works on Windows, macOS, and Linux. It will be available in version 5.0.0 which I will release soon.

**Comment by akash07k** [comment]
Hi @TolikPylypchuk Thanks a tons for implementing this ❤️
I will eagerly wait for 5.0 release and will be happy to use it in my apps.
Thanks once again 👍 
> Hi @akash07k! FYI, I've implemented simulating text entry in libuiohook myself, and it works on Windows, macOS, and Linux. It will be available in version 5.0.0 which I will release soon.

**Comment by TolikPylypchuk** [comment]
I've just released version 5.0.0 so this issue can be closed.
