### ISSUE TITLE
How to avoid sending the key to the system?

### ISSUE THREAD

**Issue by akash07k** [TolikPylypchuk/SharpHook#8]
So my question is that let's say I'm intercepting the "A" key.
Now I want then when I press this key, something else should be typed which obviously I'll handle with my application.
Now what happens is "A" is also intercepted by the text editors and "A" gets typed too. Which I do not want.
```
        private static void OnKeyPressed(object? sender, HookEventArgs e)
        {
           InputSimulator simulator = new();
            switch(e.RawEvent.Keyboard.KeyCode)
            {
                case KeyCode.VcA:
                    simulator.Keyboard.TextEntry("Hello");
                    break;
            }
        }
```
When I do this, the string which gets typed is: "haello" which should not happen.
I've seen in some libraries that we can do like this:
```e.handled = true;```

Example code:

```
            switch(e.RawEvent.Keyboard.KeyCode)
            {
                case KeyCode.VcA:
                    simulator.Keyboard.TextEntry("Hello");
e.handled = true;
                    break;
           }
```
and as soon as we do this, the key is only handled by our application and not by the system.
However there's no way to handle the key via SharpHook by using like e.handled = true
Any way to do it in SharpHook?
This is the best library and I don't want to use any other library just for this reason.

**Comment by akash07k** [comment]
Great! it works. Thanks bro. But why doesn't it work with TaskPoolGlobalHook then?

**Comment by akash07k** [comment]
Oh, I got it.
So,is there any drawback/downside to using SimpleGlobalHook instead of TaskPoolGlobalHook?
Also, since sharphook is using libuiohook under the hood, which it impact the speed of key interception?

**Comment by TolikPylypchuk** [comment]
If you're using `SimpleGlobalHook` then your event handlers should be fast. If you put `Thread.Sleep` or something long-running (like file I/O) inside your event handler, then the OS will have to wait until it's done before handling events further. With `TaskPoolGlobalHook` it's not a problem, because no matter how long your event handler will execute, it will be done on a separate thread and the OS will be able to process the event further almost instantly.

If you're doing something simple in the event handlers, then using `SimpleGlobalHook` is totally fine.

As for impacting the speed, I don't think it matters that much that a native library is used under the hood. P/Invoke obviously is not free, but it's not particularly slow, so I wouldn't worry about it.

**Comment by akash07k** [comment]
Oh, ok bro, understood.
So can't we implement the support for suppressing the events in TaskPoolGlobalHook too?

**Comment by TolikPylypchuk** [comment]
We can't because it would require that the event handler is executed synchronously, and that would defeat the purpose of `TaskPoolGlobalHook` - we already have `SimpleGlobalHook` which executes event handlers synchronously.

**Comment by akash07k** [comment]
Oh, ok

**Comment by TolikPylypchuk** [comment]
FYI, in version 4.0.0 the way to suppress events became a little more clear - `HookEventArgs` now contains the `SuppressEvent` property instead of `Reserved`. You can now do this to suppress events:

```c#
e.SuppressEvent = true;
```
