### ISSUE TITLE
Keyboard and mouse interaction freezes after program enters breakpoint

### ISSUE THREAD

**Issue by Dynesshely** [TolikPylypchuk/SharpHook#87]
The specific performance is:
After hooking the keyboard event, if the program hits a breakpoint, the mouse and keyboard operations will suddenly become extremely stuck. According to the naked eye, each mouse position update will take up to several seconds.

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for posting this issue! This is a known problem and unfortunately, this is just the way global hooks work on Windows. I'm going to add a possibility to run only keyboard or only mouse hooks so that if you hit a breakpoint inside a keyboard event handler, at least your mouse won't freeze.

I'm going to close this issue a duplicate of issue #37 - let's continue the discussion there.

**Comment by Dynesshely** [comment]
> Hi! Thanks for posting this issue! This is a known problem and unfortunately, this is just the way global hooks work on Windows. I'm going to add a possibility to run only keyboard or only mouse hooks so that if you hit a breakpoint inside a keyboard event handler, at least your mouse won't freeze.
> 
> I'm going to close this issue a duplicate of issue #37 - let's continue the discussion there.

Thank you very much for your answer.
I'm very sorry, I did a cursory check in the issues list and didn't find #37, which caused you trouble.

**Comment by TolikPylypchuk** [comment]
No problem, don't worry :)
